#!/bin/bash
touch '*\\'"Best School"\'\\*$\?\*\*\*\*\*:)         # create the file with the desired name
echo "Best School" >> '*\\'"Best School"\'\\*$\?\*\*\*\*\*:)     # add text to the file
echo "" >> '*\\'"Best School"\'\\*$\?\*\*\*\*\*:) 
